config/routes.rb
SampleApp::Application.routes.draw do

  get "activities/index"
  get "password_resets/new"
  resources :users do
    member do
      get :following, :followers
      post :notice, defaults: { format: 'js' }
      get :microposts, defaults: { format: 'atom' }
    end
  end

  namespace :api do
    resources :users, :defaults => { :format => 'xml' }
  end


  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  get 'users/:id/activate', to: 'users#activate', as: 'activate_users'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  root 'static_pages#home'













end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    UserMailer.password_reset(user).deliver if user && user.send_password_reset
    flash[:success] = "Email sent with password reset instructions."
    redirect_to root_url
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(user_params)
      flash[:success] = "Password has been reset!"
      redirect_to root_url
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.haml
= form_for @user, :url => password_reset_path(params[:id]) do |f|
  - if @user.errors.any?
    %div{:class=>"error_messages"}
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message

  %div{:class=>"field"}
    = f.label :password
    = f.password_field :password
  
  %div{:class=>"field"}
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  
  %div{:class=>"actions"}
    = f.submit "Update Password"

app/views/password_resets/new.html.haml
= form_tag password_resets_path, :method => :post do
  %div{:class=>"field"}
    = label_tag :email
    = text_field_tag :email, params[:email]
  %div{:class=>"actions"}
    = submit_tag "Reset Password"