config/routes.rb
SampleApp::Application.routes.draw do

  get "activities/index"
  get "password_resets/new"
  resources :users do
    member do
      get :following, :followers
      post :notice, defaults: { format: 'js' }
      get :microposts, defaults: { format: 'atom' }
    end
  end

  namespace :api do
    resources :users, :defaults => { :format => 'xml' }
  end


  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  get 'users/:id/activate', to: 'users#activate', as: 'activate_users'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  root 'static_pages#home'













end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  before_create :create_activation_token
  #default_scope { where state: 'active' }


  VALID_NAME_REGEX =  /[\w+\-.\s]/i
  validates :name, presence: true,
            format: { with: VALID_NAME_REGEX }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6, maximum: 50 }, :if => :validate_password?
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :replies, foreign_key: "in_reply_to_id", class_name: "Micropost"

  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_secure_password

  state_machine initial: :inactive do
    state :inactive, value: 0
    state :active, value: 1

    event :activate do
      transition :inactive => :active
    end

    event :inactivate do
      transition :active => :inactive
    end
  end

  
  #before_save { email.downcase! }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    Micropost.from_users_followed_by_including_replies(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end

  def not_notice_user
    not_notice
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end

  def self.search(search)

    if search
      where('state = ? and name LIKE ?', 1, "%#{search}%")
    else
      where(state: 1)
    end
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false)
  end

  private
    def validate_password?
      password.present? || password_confirmation.present?
    end
    def create_activation_token
      generate_token(:activation_token)
      self.activation_token_sent_at = Time.zone.now
    end

    def create_remember_token
    	self.remember_token = User.encrypt(User.new_remember_token)
    end

    def generate_token(column)
      begin
        self[column] = User.new_remember_token
      end while User.exists?(column => self[column])
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  http_basic_authenticate_with :name => "generic", :password => "generic"
  include SessionsHelper
  before_action :signed_in_user, only: [:index,:edit, :update, :destroy, :following, :followers, :notice]
  before_action :correct_user,   only: [:edit, :update, :notice]
  before_action :admin_user,    only: :destroy
  before_action :destroy_themself, only: :destroy
  before_action :already_has_account,   only: [:new, :create]

  def index 
    @users = User.search(params[:search]).paginate(page: params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.xml { render :xml => @users }
    end
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def microposts
    @user = User.find(params[:id])
    @microposts = @user.microposts
    @title = "#{@user.name} posts"
    @updated = @microposts.first.updated_at unless @microposts.empty?

    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      UserMailer.send_activation_url(@user).deliver
      flash[:success] = "You will recive activation url on mail, please check it and follow"
      redirect_to root_url
  	else
  	  render 'new'
    end
  end

  def activate
    @user = User.find_by_activation_token!(params[:id])

    if @user.activation_token_sent_at < 2.days.ago
      flash[:error] = "Activation has been expired"
      redirect_to signin_path
    elsif @user.activate!
      flash[:success] = "User has been activated!"
      sign_in @user
      redirect_to @user
    else
      flash[:error] = "User could not be activated!"
      redirect_to signin_path
    end 
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def notice
    @user = User.find(params[:id])
     respond_to do |format|
      if @user.update_attribute(:not_notice, params[:not_notice])
        if params[:not_notice] == 'true'
          @message = "You will not recive message when user follow"
        else
          @message = "You will recive notice when user follow"
        end
        flash[:success] = @message
        format.html { redirect_to @user, :notice => @message }
        format.js {}
      else
        @message = "Your changes not updated"
        flash[:error] = @message
        format.html { redirect_to @user, :notice => @message  }
        format.js {}
      end
    end 
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
  	  params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def destroy_themself
      redirect_to(root_url) if current_user == User.find(params[:id])
    end

    def already_has_account
      redirect_to(root_url) if current_user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :signed_in_user, only: [:index,:edit, :update, :destroy, :following, :followers, :notice]
  before_action :correct_user,   only: [:edit, :update, :notice]
  before_action :admin_user,    only: :destroy
  before_action :destroy_themself, only: :destroy
  before_action :already_has_account,   only: [:new, :create]

  def index 
    @users = User.search(params[:search]).paginate(page: params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @users }
    end

  end

  def new
  	@user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def microposts
    @user = User.find(params[:id])
    @microposts = @user.microposts
    @title = "#{@user.name} posts"
    @updated = @microposts.first.updated_at unless @microposts.empty?

    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      UserMailer.send_activation_url(@user).deliver
      flash[:success] = "You will recive activation url on mail, please check it and follow"
      redirect_to root_url
  	else
  	  render 'new'
    end
  end

  def activate
    @user = User.find_by_activation_token!(params[:id])

    if @user.activation_token_sent_at < 2.days.ago
      flash[:error] = "Activation has been expired"
      redirect_to signin_path
    elsif @user.activate!
      flash[:success] = "User has been activated!"
      sign_in @user
      redirect_to @user
    else
      flash[:error] = "User could not be activated!"
      redirect_to signin_path
    end 
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def notice
    @user = User.find(params[:id])
     respond_to do |format|
      if @user.update_attribute(:not_notice, params[:not_notice])
        if params[:not_notice] == 'true'
          @message = "You will not recive message when user follow"
        else
          @message = "You will recive notice when user follow"
        end
        flash[:success] = @message
        format.html { redirect_to @user, :notice => @message }
        format.js {}
      else
        @message = "Your changes not updated"
        flash[:error] = @message
        format.html { redirect_to @user, :notice => @message  }
        format.js {}
      end
    end 
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
  	  params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def destroy_themself
      redirect_to(root_url) if current_user == User.find(params[:id])
    end

    def already_has_account
      redirect_to(root_url) if current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper

	 # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_follow.html.haml
= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f|
  %div= f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  %div{:id=>"follow_form"}
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.haml
= form_for(@user) do |f|
  = render 'shared/error_messages', object: f.object 

  = f.label :name 
  = f.text_field :name 

  = f.label :email 
  = f.text_field :email 

  = f.label :password 
  = f.password_field :password 

  = f.label :password_confirmation, "Confirm Password" 
  = f.password_field :password_confirmation

  = f.submit yield(:submit_title), class: "btn btn-large btn-primary" 

app/views/users/_notice_form.html.haml
- if current_user?(@user)
  %div{:id=>"notice_form"}
    = check_box_tag :not_notice, current_user.id , current_user.not_notice, :class => "notice-mail" 
    = content_tag :span, 'Not notice me when user follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }, remote: true) do |f|
  = f.submit "Unfollow", class: "btn btn-large"

app/views/users/_user.html.haml
%li
  = gravatar_for user, size: 52 
  = link_to user.name, user 
  - if current_user.admin? && !current_user?(user)
    = link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } 

app/views/users/edit.html.haml
- provide(:title, "Edit user")
- provide(:submit_title, "Save changes")
%h1 Update your profile

%div{:class=>"row"}
  %div{:class=>"span6 offset3"} 
    = render 'users/form' 
    = gravatar_for @user 
    %a{:href=>"http://gravatar.com/emails",:target => "_blank"} change

app/views/users/index.html.haml
- provide(:title, 'All users')

%h1 All users
= form_tag users_path, :method => 'get' do 
  %p
    = text_field_tag :search, params[:search] 
    = submit_tag "Search", :name => nil

= will_paginate @users 

%ul{:class=>"users"}= render @users

= will_paginate

app/views/users/new.html.haml
- provide(:title, 'Sign up')
- provide(:submit_title, "Create my account")
%h1= yield(:title)

%div{:class=>"row"}
  %div{:class=>"span6 offset3"}= render 'users/form' 

app/views/users/notice.js.erb
$('.alert').remove();
$('.row').prepend('<div class="alert alert-success"><%= @message %></div>')

app/views/users/show.html.haml
= link_to "RSS", microposts_user_path 
- provide(:title, @user.name) 
%h1= @user.name
%div{:class=>"row"}
  %aside{:class=>"span4"}
    %section
      %h1
        = gravatar_for @user
        = @user.name
        %section= render 'shared/stats'
  %div{:class=>"span8"}
    = render 'notice_form' if signed_in?
    = render 'follow_form' if signed_in?
    - if @user.microposts.any?
      %h3 Microposts (#{@user.microposts.count})
      %ol{:class=>"microposts"}
        = render @microposts
      = will_paginate @microposts

app/views/users/show_follow.html.haml
- provide(:title, @title)
%div{:class=>"row"}
  %aside{:class=>"span4"}
    %section
      = gravatar_for @user
      %h1= @user.name
      %span= link_to "view my profile", @user
      %span
        %b Microposts: #{@user.microposts.count}
      = render 'shared/stats'
      - if @users.any?
        %div{:class=>"user_avatars"}
          - @users.each do |user|
            = link_to gravatar_for(user, size: 30), user
         
  %div{:class=>"span8"}
    %h3= @title
    - if @users.any?
      %ul{:class=>"users"}
        = render @users
      = will_paginate